site_name: OSMDiff
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: false
            heading_level: 2
            show_submodules: true
            members_order: alphabetical
            merge_init_into_class: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples/index.md
  - API Reference:
      - OSM: api/osm.md
      - OSMChange: api/osmchange.md
      - AugmentedDiff: api/augmenteddiff.md
      - ContinuousAugmentedDiff: api/continuous.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: "#"
  - smarty
  - sane_lists
