site_name: OSMDiff
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src] # search packages in src directory
          options:
            show_source: true
            show_root_heading: true
            heading_level: 1

nav:
  - Home: index.md
  - API Reference:
      - AugmentedDiff: api/augmenteddiff.md
      - ContinuousAugmentedDiff: api/continuous.md
      - OSMChange: api/osmchange.md
      - OSM: api/osm.md
  - Examples (WIP): examples/index.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: "#"
  - smarty
  - sane_lists
