

# [project]
# name = "osmdiff"
# version = "0.3.1"
# authors = [
#   { name="Martijn van Exel", email="m@rtijn.org" },
# ]
# description = "A read-only API to OpenStreetMap diffs"
# readme = "README.md"
# requires-python = ">=3.7"
# classifiers = [
#     "Programming Language :: Python :: 3",
#     "License :: OSI Approved :: MIT License",
#     "Operating System :: OS Independent",
# ]


# [project.optional-dependencies]
# test = [
#   "pytest==7.1.3",
#   "python-dateutil==2.8.2",
# ]

[tool.poetry]
authors=["Martijn van Exel"]
name="osmdiff"
description="A read-only API to OpenStreetMap diffs"
version = "0.3.2"

[tool.poetry.dependencies]
python = "^3.7"
python-dateutil = "2.8.2"
requests = "2.28.1"
typing-extensions = "^4.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
