[tool.poetry]
authors = ["Martijn van Exel <m@rtijn.org>"]
name = "osmdiff"
description = "A read-only API to OpenStreetMap diffs"
version = "0.3.2"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/osmlab/osmdiff"
repository = "https://github.com/osmlab/osmdiff"
keywords = ["openstreetmap", "osm"]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Development Status :: 5 - Production/Stable",
  "Topic :: Software Development :: Libraries :: Python Modules",
]

[tool.poetry.dependencies]
python = "^3.7"
python-dateutil = "2.8.2"
requests = "2.28.1"
typing-extensions = "^4.4.0"

[tool.poetry.dev-dependencies]
pytest = "^6.0.0"
Shapely = "^1.8.0"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/osmlab/osmdiff/issues"

[tool.poetry.group.dev.dependencies]
black = "^23.1.0"

