[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[metadata]
name = "osmdiff"

[project]
name = "osmdiff"
version = "0.3.2"
authors = [
  { name="Martijn van Exel", email="m@rtijn.org" },
]
description = "A read-only API to OpenStreetMap diffs"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "python-dateutil==2.8.2",
  "requests==2.28.1"
]

[project.urls]
"Homepage" = "https://github.com/osmlab/osmdiff"
"Bug Tracker" = "https://github.com/osmlab/osmdiff/issues"

[project.optional-dependencies]
test = [
  "pytest==7.1.3",
]