version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install PDM
          command: pip install pdm==2.15.3
      - run:
          name: Install Dependencies
          command: pdm install --dev
      - run:
          name: Run Tests
          command: pdm run pytest --cov=your_package_name

workflows:
  version: 2
  test:
    jobs:
      - test
