version: 2.1

jobs:
    build:
      runs-on: python:3.8
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.8
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install .[test]
        - name: Run tests
          run: |
            python -m pytest

