version: 2.1

orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pdm
      - run:
          command: |
            pdm run pytest --version
          name: Tests
workflows:
  main:
    jobs:
      - build
