# Recommended workflow (.github/workflows/deploy.yml)
name: Deploy Docs
on:
  push:
    branches: [main, develop]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - run: pip install mkdocs>=1.6.1 mkdocstrings>=0.26.1 mkdocstrings-python mkdocs-material>=9.5.50 mkdocs-material-extensions>=1.3.1 pymdown-extensions>=10.0.0
      - run: mkdocs gh-deploy --force
